mlx worker launch -- python3 ./src/finetune.py \
    --peft_type lora \
    --llm_model_name Qwen \
    --llm_model_path ../model/Qwen2-7B-Instruct \
    --dataset_path ../data/trainset/car_sft_trainset.json \
    --log_path ../log/car_sft_lora.log \
    --max_length 1024 \
    --lora_rank 16 \
    --task_type classification \
    --output_dir ../out/car_lora_model \
    --per_device_train_batch_size 1 \
    --num_train_epochs 1 \
    --learning_rate 1e-4 \
    --max_steps 2400 \
    --save_steps 240 \
    --save_total_limit 10 \
    --logging_steps 10 \
    --gradient_accumulation_steps 16 \